server:
   port: 8080
spring:
   application:
      name: "partsandtools"
   profiles:
      active: "prod"
   datasource:
      url: jdbc:mysql://localhost:3306/partsandtoolsdb
      username: root
      password: root

   jpa:
      show-sql: true
   sql:
      init:
         mode: always
   config:
      import: "optional:configserver:http://localhost:8071/"

   #rabbitmq:
    #  host: "localhost"
     # post: 5672
     # username: "guest"
     # password: "guest"
         
management:
   endpoints:
      web:
         exposure:
            include: "*"