server:
   port: 8080
spring:
   application:
      name: "partsandtools"
   profiles:
      active: "prod"
   datasource:
      #url: jdbc:mysql://localhost:3306/cardsdb
      #username: root
      #password: root
      url: jdbc:h2:mem:partsandtoolsdb
      driverClassName: org.h2.Driver
      username: sa
      password: ''
   h2:
      console:
         enabled: true
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
         ddl-auto: update
      show-sql: true
   #sql:
     # init:
      #   mode: always
   config:
      import: "optional:configserver:http://localhost:8071/"

   #rabbitmq:
    #  host: "localhost"
     # post: 5672
     # username: "guest"
     # password: "guest"
         
management:
   endpoints:
      web:
         exposure:
            include: "*"
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true            
   endpoint:
      shutdown:
         enabled: true
      health:
         probes:
            enabled: true           
   info:
      env:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}      
endpoints:
   shutdown:
      enabled: true

eureka:
   instance:
      perferIpAddress: true 
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://localhost:8070/eureka/
         
info:
    app:
       name: "partsandtools"
       description: "Parts and Tools Application for Aircraft Maintenace"
       version: "1.0.0"        

logging:
   level:
      com:
         aircraft:
            maintenance:
               partsandtools: DEBUG    
   pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"                                   