spring:
   config:
      activate:
         on-profile: "qa"

build:
   version: "2.0"
   
partsandtools:
   message: "Contact Details for Parts and Tools Team for any support issues in QA"
   contactDetails:
      name: "SenthilVinayaham - QA"
      email: "senthilvinayahaqam@gmail.com"
   onCallSupport:
      (777) 111-2222
      (888) 333-4444