server:
   port: 8072
   
spring:
   application:
      name: "apigateway"

   config:
      import: "optional:configserver:http://localhost:8071/"
   cloud:
      gateway:
         discovery:
            locator:
               enabled: false
               lowerCaseServiceId: true
         httpclient:
            connect-timeout: 1000
            response-timeout: 5s   
   data:
      redis:
         connect-timeout: 1000
         host: localhost
         port: 6379
         timeout: 1s

   security:
      oauth2:
         resourceserver:
            jwt:
               jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
            
management:
   endpoints:
      web:
         exposure:
            include: "*"
   endpoint:
      gateway:
         enabled: true         
   info:
      env:
         enabled: true
       
info:
    app:
       name: "apigateway"
       description: "Api Gateway for Aircraft Maintenace Microservices"
       version: "1.0.0"        

logging:
   level:
      com:
         aircraft:
            maintenance:
               apigateway: DEBUG
resilience4j.circuitbreaker:
   configs:
      default:
         slidingWindowSize: 10
         permittedNumberOfCallsInHalfOpenState: 2
         failureRateThreshold: 50
         
         
         
         
         
         waitDurationInOpenState: 10000                                     