services:

   network-deploy-service:
      networks:
         - aircraftmaintenance

   microservice-base-config:
      extends:
         service: network-deploy-service
      deploy:
         resources:
            limits:
               memory: 700m
      #environment:
       #  SPRING_RABBITMQ_HOST: "rabbit"            

   microservice-configserver-config:
      extends:
         service: microservice-base-config
      environment:
         SPRING_PROFILES_ACTIVE: default
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://configserver:8071/"       

   microservice-eureka-config:
      extends:
         service: microservice-configserver-config
      environment:
         EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
                             