apiVersion: apps/v1
kind: Deployment
metadata:
  name: partsandtools-deployment
  labels:
    app: partsandtools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partsandtools
  template:
    metadata:
      labels:
        app: partsandtools
    spec:
      containers:
      - name: accounts
        image: senvinayaham/partsandtools:WithAPIGateway
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: aircraftmaintenance-configmap
              key: ACCOUNTS_APPLICATION_NAME
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: aircraftmaintenance-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: aircraftmaintenance-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: aircraftmaintenance-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: partsandtools
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080