spring:
   application:
      name: "maintenaceConfigServer"
   profiles:
      #active: native
      active: git
   cloud:
      config:
         server:
            #native:
               #search-locations: "classpath:/config"
               #search-locations: "file:///Users//senthilvinayahammurugan//Documents//config"
            git:
               uri: "https://github.com/senvinayaham/aircraft-microservice-configs.git"
               default-lable: main
               timeout: 5
               clone-on-start: true
               force-pull: true
   #rabbitmq:
    #  host: "localhost"
     # post: 5672
      #username: "guest"
      #password: "guest"

management:
   endpoints:
      web:
         exposure:
            include: "*"
   health:
      readiness-state:
         enabled: true
      liveness-state:
         enabled: true
   endpoint:
      health:
         probes:
            enabled: true
   metrics:
      tags:
         application: ${spring.application.name}                
encrypt:
   key: "QO1E7ADEDS"

server:
   port: 8071
   
  