server:
   port: 9010

spring:
   application:
      name: "message"
   cloud:
      function:
         definition: emailmessage|smsmessage   
      stream:
         bindings:
            emailmessagesmsmessage-in-0:
               destination: send-communication
               group: ${spring.application.name}
            emailmessagesmsmessage-out-0:
               destination: communication-sent
   rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      connection-timeout: 10s
               